use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// An `AtlasUser` struct is generated by the `CustomResource` derive macro.
/// This struct represents the spec part of the custom resource definition (CRD) for the `AtlasUser` resource.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "moertel.com",
    version = "v1",
    kind = "AtlasUser",
    plural = "atlasusers",
    derive = "PartialEq",
    namespaced
)]
#[serde(rename_all = "camelCase")]
pub struct AtlasUserSpec {
    pub first_name: String,
    pub last_name: String,
    pub username: String,
    pub password: Option<String>,
    pub country: String,
    pub mobile_number: Option<String>,
    pub roles: Vec<Role>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct Role {
    org_id: Option<String>,
    group_id: Option<String>,
    role_name: RoleName,
}
// #[serde(untagged)]
// pub enum Role {
//     Group { group_id: String, role_name: RoleName },
//     Org { org_id: String, role_name: RoleName },
// }

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RoleName {
    OrgOwner,
    OrgMember,
    OrgGroupCreator,
    OrgBillingAdmin,
    OrgReadOnly,
    GroupClusterManager,
    GroupDataAccessAdmin,
    GroupDataAccessReadOnly,
    GroupDataAccessReadWrite,
    GroupOwner,
    GroupReadOnly,
    GroupSearchIndexEditor,
    GroupStreamProcessingOwner,
}
